### PR TITLE
Adding imageMirror property

### PR DESCRIPTION
**Pull request by ron94**
Fixing issue: [Mirror option is not available](https://github.com/MABelanger/react-html5-camera-photo/issues/3)

### CODE REVIEW

**Comment by MABelanger** [comment]
Cool,
Can you isImageMirror to true by default because in other app like Hangouts and others native camera app.

So in Camera/index.js : 
Camera.defaultProps = {
  isImageMirror: true,
};

**Comment by ron94** [comment]
@MABelanger Done

**Comment by ron94** [comment]
Is it required to update the version inside package.json?

**Comment by MABelanger** [comment]
Yep i will do it this evening !

**Pull request merged**
